version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: kwhjN09arED8WL
      PGDATA: /data/postgres
    ports:
      - '5432:5432'

volumes:
  postgres-db:
    driver: local
